// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    [Migration("20250202212619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Data.Entities.Referrals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredUserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefferedTrackingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5820),
                            ReferralCode = "XY7G4D",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("89562468-222a-4661-bee0-5d9b9749cd90"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5878),
                            ReferralCode = "AB8H5E",
                            ReferrerUserId = "johndoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("26a3bd92-3917-401e-98c3-fd8f8d9d02b4"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5882),
                            ReferralCode = "XY7G4D",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("f273be35-eb54-4bb5-977c-31aec7506bad"),
                            Status = "Redeemed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5885),
                            ReferralCode = "XY7G4D",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("995822ad-9064-425d-8a67-4aed6272c09b"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5888),
                            ReferralCode = "XY7G4D",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("7578daa8-8ad6-42f7-b46c-988a41bc6fd1"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 2, 16, 26, 19, 693, DateTimeKind.Local).AddTicks(5890),
                            ReferralCode = "XY7G4D",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("3adfad83-068d-4d9c-acea-881610593d06"),
                            Status = "Redeemed"
                        });
                });

            modelBuilder.Entity("Data.ReferralReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferralId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferralId");

                    b.ToTable("ReferralReports");
                });

            modelBuilder.Entity("Data.ReferralTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferralId");

                    b.ToTable("ReferralTracking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClickedAt = new DateTime(2025, 2, 2, 21, 26, 19, 693, DateTimeKind.Utc).AddTicks(6013),
                            DeviceId = "device001",
                            ReferralId = 1,
                            Source = "SMS"
                        },
                        new
                        {
                            Id = 2,
                            ClickedAt = new DateTime(2025, 2, 2, 21, 26, 19, 693, DateTimeKind.Utc).AddTicks(6014),
                            DeviceId = "device002",
                            ReferralId = 2,
                            Source = "Email"
                        });
                });

            modelBuilder.Entity("Data.ReferralReports", b =>
                {
                    b.HasOne("Data.Entities.Referrals", "Referral")
                        .WithMany("ReferralReports")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Data.ReferralTracking", b =>
                {
                    b.HasOne("Data.Entities.Referrals", "Referral")
                        .WithMany("Clicks")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Data.Entities.Referrals", b =>
                {
                    b.Navigation("Clicks");

                    b.Navigation("ReferralReports");
                });
#pragma warning restore 612, 618
        }
    }
}
