// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    [Migration("20250203160059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Data.Entities.Referrals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredUserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RefferedTrackingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8097),
                            ReferralCode = "XY7G4D",
                            ReferredUserEmail = "joe@gmail.com",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("89562468-222a-4661-bee0-5d9b9749cd90"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8150),
                            ReferralCode = "AB8H5E",
                            ReferredUserEmail = "joe@gmail.com",
                            ReferrerUserId = "johndoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("26a3bd92-3917-401e-98c3-fd8f8d9d02b4"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8153),
                            ReferralCode = "XY7G4D",
                            ReferredUserEmail = "joe@gmail.com",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("f273be35-eb54-4bb5-977c-31aec7506bad"),
                            Status = "Redeemed"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8157),
                            ReferralCode = "XY7G4D",
                            ReferredUserEmail = "Eli@gmail.com",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("995822ad-9064-425d-8a67-4aed6272c09b"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8159),
                            ReferralCode = "XY7G4D",
                            ReferredUserEmail = "kate@gmail.com",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("7578daa8-8ad6-42f7-b46c-988a41bc6fd1"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 2, 3, 11, 0, 58, 884, DateTimeKind.Local).AddTicks(8162),
                            ReferralCode = "XY7G4D",
                            ReferredUserEmail = "bill@gmail.com",
                            ReferrerUserId = "janedoe@nothingspecific.com",
                            RefferedTrackingId = new Guid("3adfad83-068d-4d9c-acea-881610593d06"),
                            Status = "Redeemed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
